RENAME TABLE `convo_participant_group_members` TO `convo_participant_team_members`;
RENAME TABLE `group_members` TO `team_members`;
RENAME TABLE `groups` TO `teams`;
ALTER TABLE `convo_participants` RENAME COLUMN `group_id` TO `team_id`;
ALTER TABLE `email_identities_authorized_org_members` RENAME COLUMN `group_id` TO `team_id`;
ALTER TABLE `email_routing_rules_destinations` RENAME COLUMN `group_id` TO `team_id`;
ALTER TABLE `convo_participant_team_members` RENAME COLUMN `group_id` TO `team_id`;
ALTER TABLE `team_members` RENAME COLUMN `group_id` TO `team_id`;
DROP INDEX `group_id_idx` ON `convo_participant_team_members`;
DROP INDEX `group_id_idx` ON `team_members`;
ALTER TABLE `convo_participants` MODIFY COLUMN `role` enum('assigned','contributor','commenter','watcher','teamMember','guest') NOT NULL DEFAULT 'contributor';
ALTER TABLE `convo_participants` ADD CONSTRAINT `team_to_convo_idx` UNIQUE(`convo_id`,`team_id`);
ALTER TABLE `email_identities_authorized_org_members` ADD CONSTRAINT `team_to_identity_idx` UNIQUE(`identity_id`,`team_id`);
ALTER TABLE `team_members` ADD CONSTRAINT `org_member_to_team_idx` UNIQUE(`team_id`,`org_member_id`);
ALTER TABLE `convo_participants` DROP INDEX `group_to_convo_idx`;
ALTER TABLE `email_identities_authorized_org_members` DROP INDEX `group_to_identity_idx`;
ALTER TABLE `team_members` DROP INDEX `org_member_to_group_idx`;
CREATE INDEX `team_id_idx` ON `convo_participant_team_members` (`team_id`);
CREATE INDEX `team_id_idx` ON `team_members` (`team_id`);