ALTER TABLE `authenticators` ADD CONSTRAINT `public_id_idx` UNIQUE(`public_id`);
ALTER TABLE `email_routing_rules_destinations` ADD CONSTRAINT `public_id_idx` UNIQUE(`public_id`);
ALTER TABLE `sessions` ADD CONSTRAINT `public_id_idx` UNIQUE(`public_id`);
CREATE INDEX `subject_id_idx` ON `convo_entries` (`subject_id`);
CREATE INDEX `author_idx` ON `convo_entries` (`author`);
CREATE INDEX `created_at_idx` ON `convo_entries` (`created_at`);
CREATE INDEX `email_message_id_idx` ON `convo_entries` (`email_message_id`);
CREATE INDEX `org_id_idx` ON `convo_entry_private_visibility_participants` (`org_id`);
CREATE INDEX `convo_member_id_idx` ON `convo_entry_private_visibility_participants` (`convo_member_id`);
CREATE INDEX `org_id_idx` ON `convo_entry_raw_html_emails` (`org_id`);
CREATE INDEX `wipe_date_idx` ON `convo_entry_raw_html_emails` (`wipe_date`);
CREATE INDEX `org_id_idx` ON `convo_entry_replies` (`org_id`);
CREATE INDEX `entry_source_id_idx` ON `convo_entry_replies` (`convo_message_source_id`);
CREATE INDEX `entry_reply_id_idx` ON `convo_entry_replies` (`convo_message_reply_id`);
CREATE INDEX `created_at_idx` ON `convo_entry_replies` (`created_at`);
CREATE INDEX `participant_id_idx` ON `convo_entry_seen_timestamps` (`participant_id`);
CREATE INDEX `participant_id_idx` ON `convo_seen_timestamps` (`participant_id`);
CREATE INDEX `created_at_idx` ON `convos` (`created_at`);
CREATE INDEX `rule_id_idx` ON `email_routing_rules_destinations` (`rule_id`);
CREATE INDEX `team_id_idx` ON `email_routing_rules_destinations` (`team_id`);
CREATE INDEX `org_member_id_idx` ON `email_routing_rules_destinations` (`org_member_id`);