name: autofix.ci
on:
  pull_request:
    types: [review_requested, ready_for_review]
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20'

      - run: pnpm install

      - name: Run ESLint
        run: pnpm fix

      - name: Run Prettier
        run: pnpm format

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
